<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Unpaid Tenants Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            line-height: 1.4;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
        }
        .header h1 {
            color: #2c3e50;
            margin-bottom: 5px;
        }
        .header p {
            color: #7f8c8d;
            margin: 0;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f8f9fa;
            font-weight: bold;
        }
        .total-row {
            font-weight: bold;
            background-color: #f8f9fa;
        }
        .amount {
            text-align: right;
        }
        .footer {
            margin-top: 30px;
            text-align: center;
            font-size: 10px;
            color: #7f8c8d;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Unpaid Tenants Report</h1>
        <p>For the month of {{ $month }}</p>
        <p>Generated for: {{ $owner->fname }} {{ $owner->lname }}</p>
        <p>Generated on: {{ now()->format('F d, Y') }}</p>
    </div>

    @if($unpaidTenants->isEmpty())
        <p style="text-align: center; color: #27ae60;">
            All tenants have paid for {{ $month }}
        </p>
    @else
        <table>
            <thead>
                <tr>
                    <th>Property</th>
                    <th>Tenant</th>
                    <th>Contact</th>
                    <th>Due Date</th>
                    <th>Amount</th>
                </tr>
            </thead>
            <tbody>
                @foreach($unpaidTenants as $tenant)
                    <tr>
                        <td>{{ $tenant['property'] }}</td>
                        <td>{{ $tenant['tenant'] }}</td>
                        <td>
                            Phone: {{ $tenant['contact']['phone'] }}<br>
                            Email: {{ $tenant['contact']['email'] }}
                        </td>
                        <td>{{ $tenant['due_date']->format('M d, Y') }}</td>
                        <td class="amount">
                            ₱{{ number_format($tenant['amount'], 2) }}
                            <br>
                            <small>
                                Rent: ₱{{ number_format($tenant['rent'], 2) }}
                                @if($tenant['utilities'] > 0)
                                    <br>Utilities: ₱{{ number_format($tenant['utilities'], 2) }}
                                @endif
                            </small>
                        </td>
                    </tr>
                @endforeach
                <tr class="total-row">
                    <td colspan="4" style="text-align: right;">Total Unpaid Amount:</td>
                    <td class="amount">₱{{ number_format($totalUnpaid, 2) }}</td>
                </tr>
            </tbody>
        </table>
    @endif

    <div class="footer">
        <p>This is a computer-generated report. No signature is required.</p>
        <p>Generated by {{ config('app.name') }}</p>
    </div>
</body>
</html> 